# Generated by Django 5.1.5 on 2025-01-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remizotron9000', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirefighterInSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('firefighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remizotron9000.firefighter')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remizotron9000.squad')),
            ],
            options={
                'unique_together': {('squad', 'firefighter')},
            },
        ),
    ]
